// <auto-generated />
namespace Polycore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Evurryting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Evurryting));
        
        string IMigrationMetadata.Id
        {
            get { return "201601111221245_Evurryting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
